"""init tabel mahasiswa, kelas, dan undangan

Revision ID: 267d7f91ccf6
Revises: 
Create Date: 2023-05-07 03:49:42.643273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267d7f91ccf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nim')
    )
    op.create_table('kelas',
    sa.Column('tutor_id', sa.Integer(), nullable=True),
    sa.Column('namakelas', sa.String(), nullable=False),
    sa.Column('waktumulai', sa.Date(), nullable=False),
    sa.Column('waktuselesai', sa.Date(), nullable=False),
    sa.Column('tipe', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tutor_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ikut_kelas',
    sa.Column('kelas_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('kelas_id', 'mahasiswa_id')
    )
    op.create_table('kelasonline',
    sa.Column('lokasi', sa.String(), nullable=False),
    sa.Column('kebutuhan', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kelasonsite',
    sa.Column('link_meet', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['kelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('undangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(), nullable=False),
    sa.Column('is_created', sa.Integer(), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['mahasiswa.id'], ),
    sa.ForeignKeyConstraint(['kelas_id'], ['kelas.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['mahasiswa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('undangan')
    op.drop_table('kelasonsite')
    op.drop_table('kelasonline')
    op.drop_table('ikut_kelas')
    op.drop_table('kelas')
    op.drop_table('mahasiswa')
    # ### end Alembic commands ###
